version: 1.4.{build}
os: Visual Studio 2017
platform: x64

install:
- ps: Install-PackageProvider -Name NuGet -Force
- ps: Install-Module PsScriptAnalyzer -Force

configuration:
- Debug
- Release

environment:
  solutionname: VMEM.sln

matrix:
  fast_finish: true

before_build:
- ps: >-
    if ($Env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/CHECK_WHITESPACE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/ps_analyze.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        perl utils/sort_solution check
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        ./utils/check_sdk_version.py -d .
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
    }

build_script:
- ps: msbuild src\$Env:solutionname /property:Configuration=$Env:CONFIGURATION /m /v:m

after_build:
- ps: utils/CREATE-ZIP.ps1 -b $Env:CONFIGURATION

test_script:
- ps: >-
    if ($true) {
        cd src\test
        md C:\temp
        echo "`$Env:NON_PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
        echo "`$Env:PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
        echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
        echo "`$Env:VMEM_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
        echo "`$Env:TM = `"1`"" >> testconfig.ps1

        write-output "config = {
    'unittest_log_level': 1,
    'pmem_fs_dir': 'C:\\temp',
    'non_pmem_fs_dir': 'C:\\temp',
    'tm': True,
    'test_type': 'check',
    'fs': 'all',
    'fs_dir_force_pmem': 1,
    'keep_going': False,
    'timeout': '4m',
    'build': 'debug',
    'force_enable': None,
    }" | out-file "testconfig.py" -encoding utf8

        if ($Env:CONFIGURATION -eq "Debug") {
            ./RUNTESTS.ps1 -b debug -o 4m
            if ($?) {
                ./RUNTESTS.py -b debug
            }
        }
        if ($Env:CONFIGURATION -eq "Release") {
            ./RUNTESTS.ps1 -b nondebug -o 4m
            if ($?) {
                ./RUNTESTS.py -b release
            }
        }
    }

artifacts:
- path: 'src\x64\*.zip'
  name: VMEM

- path: '*examples*.zip'
  name: VMEM_examples
