version: 1.4.{build}
os: Visual Studio 2017
platform: x64

install:
- ps: Install-PackageProvider -Name NuGet -Force
- ps: Install-Module PsScriptAnalyzer -Force

configuration:
- Debug
- Release

environment:
  solutionname: VMEM.sln

matrix:
  fast_finish: true

before_build:
- ps: >-
    if ($Env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/CHECK_WHITESPACE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/ps_analyze.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        perl utils/sort_solution check
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        ./utils/check_sdk_version.py -d .
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
    }

build_script:
- ps: msbuild src\$Env:solutionname /property:Configuration=$Env:CONFIGURATION /m /v:m

after_build:
- ps: utils/CREATE-ZIP.ps1 -b $Env:CONFIGURATION

test_script:
- ps: >-
    if ($true) {
        cd src\test
        md C:\temp
        echo "`$Env:NON_PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
        echo "`$Env:PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
        echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
        echo "`$Env:PMDK_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
        echo "`$Env:TM = `"1`"" >> testconfig.ps1
    }

artifacts:
- path: 'src\x64\*.zip'
  name: VMEM

- path: '*examples*.zip'
  name: VMEM_examples
